---

- name: Install ruby via rbenv
  shell: "rbenv install {{ ruby_version }}"
  become: yes
  become_user: "{{ user_name }}"
  environment:
    RUBY_CONFIGURE_OPTS: --disable-install-doc
    PATH: "{{ ruby_rbenv_path }}/bin:{{ ansible_env.PATH }}"
  register: ruby_install_result
  changed_when: ruby_install_result.rc == 0
  failed_when: "ruby_install_result.rc != 0 and 'already exists' not in ruby_install_result.stderr"
  tags: ruby
