---

- name: Install dependencies
  apt:
    name: "{{ ruby_install_dependency }}"
  with_items:
    - autoconf
    - bison
    - build-essential
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
    - libncurses5-dev
    - libreadline-dev
    - libssl-dev
    - libyaml-dev
    - zlib1g-dev
  loop_control:
    loop_var: ruby_install_dependency
  tags: ruby

- name: Include _setup_rbenv task
  include_role:
    name: ruby
    tasks_from: _setup_rbenv
  tags: ruby

- name: Include _install_ruby task
  include_role:
    name: ruby
    tasks_from: _install_ruby
  tags: ruby

- name: Include _set_global_ruby task
  include_role:
    name: ruby
    tasks_from: _set_global_ruby
  tags: ruby
