---

- name: Include tasks
  include_role:
    name: ruby
    tasks_from: "{{ item }}"
  with_first_found:
    - "{{ lower_distribution }}.yml"
    - "{{ lower_os_family }}.yml"
  tags: ruby

- name: rbenv which ruby
  shell: rbenv which ruby
  become: yes
  become_user: "{{ user_name }}"
  environment:
    PATH: "{{ ruby_rbenv_path }}/bin:{{ ansible_env.PATH }}"
  register: ruby_executable_file
  tags: ruby

- name: ruby --version
  shell: "{{ ruby_executable_file.stdout }} --version"
  register: ruby_installed_version
  become: yes
  become_user: "{{ user_name }}"
  tags: ruby

- name: Installed version
  debug:
    msg: "installed: {{ ruby_installed_version.stdout }}"
  tags: ruby
