---

- name: Include tasks
  include_role:
    name: ruby
    tasks_from: "{{ item }}"
  with_first_found:
    - "{{ lower_distribution }}.yml"
    - "{{ lower_os_family }}.yml"
  tags: ruby

- name: git clone rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: "{{ ruby_rbenv_path }}"
  environment:
    PATH: "/opt/git/git-{{ git_version }}/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user_name }}"
  tags: ruby

- name: make rbenv
  shell: src/configure && make -C src
  args:
    chdir: "{{ ruby_rbenv_path }}"
  become: yes
  become_user: "{{ user_name }}"
  tags: ruby

- name: Execute rbenv init
  shell: rbenv init -
  become: yes
  become_user: "{{ user_name }}"
  environment:
    PATH: "{{ ruby_rbenv_path }}/bin:{{ ansible_env.PATH }}"
  register: rbenv_init_result
  tags: ruby

- name: Add environment path
  blockinfile:
      path: ~/.bashrc
      block: |
        export PATH="$HOME/.rbenv/bin:$PATH"
        {{ rbenv_init_result }}
  become: yes
  become_user: "{{ user_name }}"
  tags: ruby

- name: git clone ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: "{{ ruby_rbenv_path }}/plugins/ruby-build"
    version: v20180329
  environment:
    PATH: "/opt/git/git-{{ git_version }}/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user_name }}"
  tags: ruby

- name: rbenv install --list
  shell: rbenv install --list
  become: yes
  become_user: "{{ user_name }}"
  environment:
    PATH: "{{ ruby_rbenv_path }}/bin:{{ ansible_env.PATH }}"
  register: ruby_available_versions
  tags: ruby

- name: Ruby available versions
  debug:
    var: ruby_available_versions.stdout_lines
  tags: ruby

- name: "Check that ruby v{{ ruby_version }} is installed"
  stat:
    path: "{{ ruby_rbenv_path }}/versions/{{ ruby_version }}"
  register: ruby_installed_dir
  tags: ruby

- name: Install ruby via rbenv
  when: not ruby_installed_dir.stat.exists
  shell: "rbenv install {{ ruby_version }} && rbenv global {{ ruby_version }}"
  become: yes
  become_user: "{{ user_name }}"
  environment:
    RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    PATH: "{{ ruby_rbenv_path }}/bin:{{ ansible_env.PATH }}"
  tags: ruby

- name: rbenv which ruby
  shell: rbenv which ruby
  become: yes
  become_user: "{{ user_name }}"
  environment:
    PATH: "{{ ruby_rbenv_path }}/bin:{{ ansible_env.PATH }}"
  register: ruby_executable_file
  tags: ruby

- name: ruby --version
  shell: "{{ ruby_executable_file.stdout }} --version"
  register: ruby_installed_version
  become: yes
  become_user: "{{ user_name }}"
  tags: ruby

- name: Installed version
  debug:
    msg: "installed: {{ ruby_installed_version.stdout }}"
  tags: ruby
