version: 2
jobs:
  centos:
    docker:
      - image: centos:7.4.1708
    steps:
      # - run: &install_commands
      #     name: Install commands
      #     command: |
      #       yum -y install git
      - checkout
      - run:
          name: Install ansible
          command: |
            yum -y install curl gcc python-devel
            curl -fsSL https://bootstrap.pypa.io/get-pip.py | python2
            pip2 install ansible==2.5.0
      - run: &ansible_info
          name: Ansible info
          command: |
            cd ansible
            ansible --version
            ansible localhost -m setup
      - run: &ansible_test
          name: Ansible Test
          command: |
            cd ansible
            ansible-playbook playbooks/mastodon-setup.yml
  ubuntu:
    docker:
      - image: ubuntu:16.04
    steps: &debian
      # - run:
      #     <<: *install_commands
      #     command: |
      #       apt-get update && apt-get -y install git
      - checkout
      - run:
          name: Install ansible
          command: |
            apt update && apt -y install curl build-essential python-dev
            curl -fsSL https://bootstrap.pypa.io/get-pip.py | python2
            pip2 install ansible==2.5.0
      - run: *ansible_info
      - run: *ansible_test
  debian:
    docker:
      - image: debian:stretch
    steps: *debian
workflows:
  version: 2
  ansible-mastodon-test:
    jobs:
      - centos
      - ubuntu
      - debian
