---

- name: apt update
  apt:
    name: "*"
    update_cache: yes
  tags: common

- name: Install packages
  apt:
    name: "{{ common_install_package }}"
  with_items: "{{ common_install_packages }}"
  loop_control:
    loop_var: common_install_package
  tags: common

- name: Include _swap.yml when enable_swap is true
  when: enable_swap
  include_role:
    name: common
    tasks_from: _swap
  tags: common
