---

- name: Output variables
  debug:
    msg: [
      " ============================================================ ",
      " Set up for '{{ stage }}' ",
      " ********** Environment ********** ",
      " OS family        : {{ ansible_os_family }} ",
      " Distribution     : {{ ansible_distribution }} ",
      " docker           : {% if is_docker %}Yes{% else %}No{% endif %} ",
      " use swap         : {% if enable_swap %}Yes (size={{ swap_size }}MB){% else %}No{% endif %} ",
      " ********** Info ********** ",
      " domain           : {{ domain_name }} ",
      " email            : {{ email }} ",
      " skip letsencrypt : {% if skip_letsencrypt %}Yes{% else %}No{% endif %} ",
      " DB password      : - secret -",
      "============================================================ "]
  tags: common

- name: "Include {{ ansible_distribution }} vars"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ lower_distribution }}.yml"
    - "{{ lower_os_family }}.yml"
  tags: common

- name: Include tasks
  include_role:
    name: common
    tasks_from: "{{ item }}"
  with_first_found:
    - "{{ lower_distribution }}.yml"
    - "{{ lower_os_family }}.yml"
  tags: common

- name: Create temp directory
  file:
    path: "{{ temp_directory }}"
    state: directory
  tags: common
