---

- name: Install dependencies
  apt:
    name: "{{ git_install_dependency }}"
  with_items:
    - autoconf
    - build-essential
    - gettext
    - libcurl4-gnutls-dev
    - libexpat1-dev
    - libssl-dev
    - libz-dev
  loop_control:
    loop_var: git_install_dependency
  tags: git

- name: Include _download task
  include_role:
    name: git
    tasks_from: _download
  tags: git

- name: Include _unarchive task
  include_role:
    name: git
    tasks_from: _unarchive
  tags: git

- name: "Check that git version is v{{ git_version }}"
  shell: git --version
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: git_current_version
  failed_when: git_current_version.rc not in [0, 127]
  tags: git

- name: "Include _make task if git version isn't {{ git_version }}"
  when: git_version not in git_current_version.stdout
  include_role:
    name: git
    tasks_from: _make
  tags: git

- name: Include _add_symbolic_link task
  include_role:
    name: git
    tasks_from: _add_symbolic_link
  tags: git
