---

- name: Install dependencies
  apt:
    name: "{{ git_install_dependency }}"
  with_items:
    - autoconf
    - build-essential
    - gettext
    - libcurl4-gnutls-dev
    - libexpat1-dev
    - libssl-dev
    - libz-dev
  loop_control:
    loop_var: git_install_dependency
  tags: git
