---

- name: Include tasks
  include_role:
    name: git
    tasks_from: "{{ item }}"
  with_first_found:
    - "{{ lower_distribution }}.yml"
    - "{{ lower_os_family }}.yml"
  tags: git

- name: Download tarball
  get_url:
    url: "https://github.com/git/git/archive/v{{ git_version }}.tar.gz"
    dest: "/var/tmp/git-{{ git_version }}.tar.gz"

- name: Unarchive
  unarchive:
    src: "/var/tmp/git-{{ git_version }}.tar.gz"
    dest: "/opt"
    extra_opts:
      - "--no-same-owner"
    remote_src: yes
  tags: git

- name: Install
  shell: "make configure && ./configure --prefix={{ git_install_path }} && make all && make install"
  args:
    chdir: "{{ git_install_path }}"
  tags: git

- name: Set path
  template:
    src: git.sh.j2
    dest: /etc/profile.d/git.sh
  tags: git

- name: git --version
  shell: git --version
  environment:
    PATH: "{{ git_install_path }}/bin:{{ ansible_env.PATH }}"
  register: git_installed_version
  tags: git

- name: Installed version
  debug:
    msg: "installed: {{ git_installed_version.stdout }}"
  tags: git

