---

- name: Include tasks
  include_role:
    name: git
    tasks_from: "{{ item }}"
  with_first_found:
    - "{{ lower_distribution }}.yml"
    - "{{ lower_os_family }}.yml"
  tags: git

- name: git --version
  shell: git --version
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: git_installed_version
  tags: git

- name: Installed version
  debug:
    msg: "installed: {{ git_installed_version.stdout }}"
  tags: git

