---

- name: "Include tasks"
  include_role:
    name: nginx
    tasks_from: "{{ item }}"
  with_first_found:
    - "{{ lower_distribution }}.yml"
    - "{{ lower_os_family }}.yml"
  tags: nginx

- name: Remove default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Start nginx
  when: not is_docker
  systemd:
    name: nginx
    state: started
    enabled: yes
  tags: nginx

- name: nginx -v
  shell: nginx -v
  register: nginx_installed_version
  tags: nginx

- name: Installed version
  debug:
    msg: "installed: {{ nginx_installed_version.stderr }}"
  tags: nginx
