---

- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL yum repo
    enabled: no
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgkey: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
  tags: mastodon

- name: Add RPM Fusion free repository
  yum:
    name: https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm

- name: Install dependencies
  yum:
    name: "{{ mastodon_install_dependency }}"
    enablerepo: epel
  with_items:
    - ImageMagick           # image processing
    - ffmpeg                # movie processing
    - file                  # @see https://github.com/tootsuite/mastodon/pull/868
    - libxml2               # RubyGems nokogiri
    - libxml2-devel         #   "
    - libxslt               #   "
    - libxslt-devel         #   "
    - protobuf-devel        # RubyGems cld3
    - libicu-devel          # RubyGems charlock_holmes
    - gcc                   #   "
    - gcc-c++               #   "
    - libidn-devel          # RubyGems idn-ruby
    - postgresql10-devel    # RubyGems pg
  loop_control:
    loop_var: mastodon_install_dependency
  tags: mastodon

- name: Include redis main task
  include_role:
    name: redis
  tags: mastodon

- name: Include _clone_mastodon tasks
  include_role:
    name: mastodon
    tasks_from: _clone_mastodon
  tags: mastodon

- name: Include _install_bundler tasks
  include_role:
    name: ruby
    tasks_from: _install_bundler
  tags: mastodon

- name: Include _install_gem_dependencies tasks
  include_role:
    name: ruby
    tasks_from: _install_gem_dependencies
  tags: mastodon

- name: Include _install_node_dependencies tasks
  include_role:
    name: yarn
    tasks_from: _install_node_dependencies
  tags: mastodon

- name: Include _obtain_certificate tasks
  include_role:
    name: mastodon
    tasks_from: _obtain_certificate
  tags: mastodon

- name: Include _add_db_user tasks
  include_role:
    name: postgresql
    tasks_from: _add_db_user
  tags: mastodon

- name: Include _set_mastodon_services tasks
  include_role:
    name: mastodon
    tasks_from: _set_mastodon_services
  tags: mastodon
