---

- name: Install dependencies
  yum:
    name: "{{ item }}"
  with_items:
    - protobuf-devel        # gem install cld3
    - libicu-devel          # gem install charlock_holmes
    - gcc                   #   "
    - gcc-c++               #   "
    - libidn-devel          # gem install idn-ruby
    - postgresql10-devel    # gem install pg
