---

- name: Install dependencies
  yum:
    name: "{{ item }}"
  with_items:
    - protobuf-devel        # gem install cld3
    - libicu-devel          # gem install charlock_holmes
    - gcc                   #   "
    - gcc-c++               #   "
    - libidn-devel          # gem install idn-ruby
    - postgresql10-devel    # gem install pg

- name: git clone mastodon
  git:
    repo: https://github.com/tootsuite/mastodon.git
    dest: "{{ mastodon_path }}"
    version: "{{ mastodon_version }}"
  environment:
    PATH: "/opt/git/git-{{ git_version }}/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user_name }}"
  tags: mastodon

- name: Instal bundler
  gem:
    name: bundler
    user_install: no
  environment:
    PATH: "{{ ruby_rbenv_path }}/versions/{{ ruby_version }}/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user_name }}"
  tags: mastodon

- name: getconf _NPROCESSORS_ONLN
  shell: getconf _NPROCESSORS_ONLN
  register: cpu_num
  tags: mastodon

- name: bundle config
  shell: "bundle config build.pg --with-pg-config={{ postgresql_path }}/bin/pg_config"
  args:
    chdir: "{{ mastodon_path }}"
  environment:
    PATH: "{{ ruby_rbenv_path }}/versions/{{ ruby_version }}/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user_name }}"

- name: Install ruby dependencies
  bundler:
    deployment_mode: yes
    exclude_groups:
      - development
      - test
    extra_args: "-j{{ cpu_num.stdout }}"
    chdir: "{{ mastodon_path }}"
  environment:
    PATH: "{{ ruby_rbenv_path }}/versions/{{ ruby_version }}/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user_name }}"
  tags: mastodon

# no yarn module yet
# @see https://github.com/ansible/ansible/pull/19026
- name: Install node.js dependencies
  shell: yarn install --pure-lockfile
  args:
    chdir: "/home/{{ user_name }}/live"
  become: yes
  become_user: "{{ user_name }}"
  tags: mastodon
