---

- name: Install dependencies
  apt:
    name: "{{ mastodon_install_dependency }}"
  with_items:
    - redis-server        # redis
    - redis-tools         #   "
    - pkg-config          # gem install cld3
    - libprotobuf-dev     #   "
    - protobuf-compiler   #   "
    - libicu-dev          # gem install charlock_holmes
    - libidn11-dev        # gem install idn-ruby
    - libpq-dev           # gem install pg
  loop_control:
    loop_var: mastodon_install_dependency
  tags: mastodon
    # - imagemagick
    # - ffmpeg
    # libxml2-dev
    # libxslt1-dev
    # file
    # g++
    # gcc
    # bison
    # build-essential
    # libssl-dev
    # libyaml-dev
    # libreadline6-dev
    # zlib1g-dev
    # libncurses5-dev
    # libffi-dev
    # libgdbm3
    # libgdbm-dev
