---

- name: Install dependencies
  apt:
    name: "{{ mastodon_install_dependency }}"
  with_items:
    - imagemagick         # image processing
    - ffmpeg              # movie processing
    - file                # @see https://github.com/tootsuite/mastodon/pull/868
    - libxml2             # RubyGems nokogiri
    - libxml2-dev         #   "
    - libxslt1-dev        #   "
    - redis-server        # redis
    - redis-tools         #   "
    - pkg-config          # RubyGems cld3
    - libprotobuf-dev     #   "
    - protobuf-compiler   #   "
    - libicu-dev          # RubyGems charlock_holmes
    - libidn11-dev        # RubyGems idn-ruby
    - libpq-dev           # RubyGems pg
  loop_control:
    loop_var: mastodon_install_dependency
  tags: mastodon
