---

- name: Install dependencies
  apt:
    name: "{{ mastodon_install_dependency }}"
  with_items:
    - imagemagick         # for image processing
    - ffmpeg              # for movie processing
    - redis-server        # redis
    - redis-tools         #   "
    - pkg-config          # gem install cld3
    - libprotobuf-dev     #   "
    - protobuf-compiler   #   "
    - libicu-dev          # gem install charlock_holmes
    - libidn11-dev        # gem install idn-ruby
    - libpq-dev           # gem install pg
  loop_control:
    loop_var: mastodon_install_dependency
  tags: mastodon
