---

# - name: "Include {{ ansible_distribution }} vars"
#   include_vars: "{{ item }}"
#   with_first_found:
#     - "{{ lower_distribution }}.yml"
#     - "{{ lower_os_family }}.yml"
#   tags: mastodon

- name: Include tasks
  include_role:
    name: mastodon
    tasks_from: "{{ item }}"
  with_first_found:
    - "{{ lower_distribution }}.yml"
    - "{{ lower_os_family }}.yml"
  tags: mastodon

- name: Obtain SSL certificate
  when: not is_test
  shell: "./certbot-auto certonly --standalone --agree-tos --non-interactive --domain {{ domain_name }} --email {{ email }}"
  args:
    chdir: "{{ letsencrypt_certbot_path }}"
    creates: "/etc/letsencrypt/live/{{ domain_name }}"
  tags: mastodon

# todo: add cron job

# - name: Add conf.d config
#   template:
#     src: "mastodon.conf.j2"
#     dest: "/etc/nginx/conf.d/mastodon.conf"
#     # validate: bash -c 'nginx -t -c /dev/stdin <<< "events {worker_connections 1;} http { include %s; }"'
#   notify:
#     - "Reload nginx"
#   tags: nginx

- name: Add DB user
  when: ansible_virtualization_type != "docker"
  postgresql_user:
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_user_password | password_hash('sha512') }}"
    encrypted: yes
    role_attr_flags: CREATEDB
  become: yes
  become_user: postgres
  tags: postgresql
