---

- name: "Include {{ ansible_distribution }} vars"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ lower_distribution }}.yml"
    - "{{ lower_os_family }}.yml"
  tags: mastodon

- name: Include tasks
  include_role:
    name: mastodon
    tasks_from: "{{ item }}"
  with_first_found:
    - "{{ lower_distribution }}.yml"
    - "{{ lower_os_family }}.yml"
  tags: mastodon

- name: Start redis
  when: ansible_virtualization_type != "docker"
  systemd:
    name: redis
    enabled: yes
    state: started
  tags: mastodon

- name: git clone mastodon
  git:
    repo: https://github.com/tootsuite/mastodon.git
    dest: "{{ mastodon_path }}"
    version: "{{ mastodon_version }}"
  environment:
    PATH: "{{ git_install_path }}/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user_name }}"
  tags: mastodon

- name: Install bundler
  gem:
    name: bundler
    user_install: no
  environment:
    PATH: "{{ ruby_rbenv_path }}/versions/{{ ruby_version }}/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user_name }}"
  tags: mastodon

- name: getconf _NPROCESSORS_ONLN
  shell: getconf _NPROCESSORS_ONLN
  register: cpu_num
  tags: mastodon

- name: bundle config
  shell: "bundle config build.pg --with-pg-config={{ postgresql_pg_config_path }}/bin/pg_config"
  args:
    chdir: "{{ mastodon_path }}"
  environment:
    PATH: "{{ ruby_rbenv_path }}/versions/{{ ruby_version }}/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user_name }}"

- name: Install ruby dependencies
  bundler:
    deployment_mode: yes
    exclude_groups:
      - development
      - test
    extra_args: "-j{{ cpu_num.stdout }}"
    chdir: "{{ mastodon_path }}"
  environment:
    PATH: "{{ ruby_rbenv_path }}/versions/{{ ruby_version }}/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user_name }}"
  tags: mastodon

# no yarn module yet
# @see https://github.com/ansible/ansible/pull/19026
- name: Install node.js dependencies
  shell: yarn install --pure-lockfile
  args:
    chdir: "/home/{{ user_name }}/live"
  become: yes
  become_user: "{{ user_name }}"
  tags: mastodon

- name: Check that ssl certificate exists
  stat:
    path: "/etc/letsencrypt/live/{{ domain_name }}"
  register: mastodon_certificate
  tags: mastodon

- name: Add nginx config
  when: not mastodon_certificate.stat.exists
  template:
    src: mastodon.conf.j2
    dest: /etc/nginx/conf.d/mastodon.conf
    validate: bash -c 'nginx -t -c /dev/stdin <<< "events {worker_connections 1;} http { include %s; }"'
  tags: mastodon

- name: Reload nginx
  when: ansible_virtualization_type != "docker"
  systemd:
    name: nginx
    state: reloaded
  tags: mastodon

- name: Obtain SSL certificate
  when: not is_test
  shell: "./certbot-auto certonly --non-interactive --agree-tos --webroot --domain {{ domain_name }} --email {{ email }} --webroot-path /home/{{ user_name }}/live/public/"
  args:
    chdir: "{{ letsencrypt_certbot_path }}"
    creates: "/etc/letsencrypt/live/{{ domain_name }}"
  tags: mastodon

- name: Remove comment out of mastodon.conf
  replace:
    path: /etc/nginx/conf.d/mastodon.conf
    regexp: '^#(\s+)ssl_certificate(.*)$'
    replace: '\1ssl_certificate\2'
  notify:
    - Reload nginx
  tags: mastodon

- name: Create cron job
  when: not is_test
  template:
    src: letsencrypt-renew.sh.j2
    dest: /etc/cron.daily/letsencrypt-renew.sh
    mode: u+x
  notify:
    - Restart cron
  tags: mastodon

- name: Add DB user
  when: ansible_virtualization_type != "docker"
  postgresql_user:
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_user_password | password_hash('sha512') }}"
    encrypted: yes
    role_attr_flags: CREATEDB
  become: yes
  become_user: postgres
  tags: mastodon

- name: Add mastodon systemd services
  template:
    src: "etc/systemd/system/{{ mastodon_service }}.j2"
    dest: "/etc/systemd/system/{{ mastodon_service }}"
  with_items: &mastodon_services
    - mastodon-web.service
    - mastodon-sidekiq.service
    - mastodon-streaming.service
  loop_control:
    loop_var: mastodon_service
  notify:
    - Daemon reload
  tags: mastodon

- name: Set mastodon services enabled
  when: ansible_virtualization_type != "docker"
  systemd:
    name: "{{ item }}"
    enabled: yes
  with_items: *mastodon_services
  tags: mastodon

- name: Add cron env
  when: not is_test
  cron:
    name: RAILS_ENV
    env: yes
    value: production
  tags: mastodon

- name: Add cron
  when: not is_test
  cron:
    name: Remote media attachment cache cleanup
    special_time: daily
    job: "cd /home/mastodon/live && /home/mastodon/.rbenv/shims/bundle exec rake mastodon:media:remove_remote"
  notify:
    - Restart cron
  tags: mastodon
