---

# - name: "Include {{ ansible_distribution }} vars"
#   include_vars: "{{ item }}"
#   with_first_found:
#     - "{{ lower_distribution }}.yml"
#     - "{{ lower_os_family }}.yml"
#   tags: mastodon

- name: Include tasks
  include_role:
    name: mastodon
    tasks_from: "{{ item }}"
  with_first_found:
    - "{{ lower_distribution }}.yml"
    - "{{ lower_os_family }}.yml"
  tags: mastodon

- name: git clone mastodon
  git:
    repo: https://github.com/tootsuite/mastodon.git
    dest: "{{ mastodon_path }}"
    version: "{{ mastodon_version }}"
  environment:
    PATH: "{{ git_install_path }}/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user_name }}"
  tags: mastodon

- name: Instal bundler
  gem:
    name: bundler
    user_install: no
  environment:
    PATH: "{{ ruby_rbenv_path }}/versions/{{ ruby_version }}/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user_name }}"
  tags: mastodon

- name: getconf _NPROCESSORS_ONLN
  shell: getconf _NPROCESSORS_ONLN
  register: cpu_num
  tags: mastodon

- name: bundle config
  shell: "bundle config build.pg --with-pg-config={{ postgresql_pg_config_path }}/bin/pg_config"
  args:
    chdir: "{{ mastodon_path }}"
  environment:
    PATH: "{{ ruby_rbenv_path }}/versions/{{ ruby_version }}/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user_name }}"

- name: Install ruby dependencies
  bundler:
    deployment_mode: yes
    exclude_groups:
      - development
      - test
    extra_args: "-j{{ cpu_num.stdout }}"
    chdir: "{{ mastodon_path }}"
  environment:
    PATH: "{{ ruby_rbenv_path }}/versions/{{ ruby_version }}/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user_name }}"
  tags: mastodon

# no yarn module yet
# @see https://github.com/ansible/ansible/pull/19026
- name: Install node.js dependencies
  shell: yarn install --pure-lockfile
  args:
    chdir: "/home/{{ user_name }}/live"
  become: yes
  become_user: "{{ user_name }}"
  tags: mastodon

- name: Obtain SSL certificate
  when: not is_test
  shell: "./certbot-auto certonly --standalone --agree-tos --non-interactive --domain {{ domain_name }} --email {{ email }}"
  args:
    chdir: "{{ letsencrypt_certbot_path }}"
    creates: "/etc/letsencrypt/live/{{ domain_name }}"
  tags: mastodon

# todo: add cron job

# - name: Add conf.d config
#   template:
#     src: "mastodon.conf.j2"
#     dest: "/etc/nginx/conf.d/mastodon.conf"
#     # validate: bash -c 'nginx -t -c /dev/stdin <<< "events {worker_connections 1;} http { include %s; }"'
#   notify:
#     - "Reload nginx"
#   tags: mastodon

- name: Add DB user
  when: ansible_virtualization_type != "docker"
  postgresql_user:
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_user_password | password_hash('sha512') }}"
    encrypted: yes
    role_attr_flags: CREATEDB
  become: yes
  become_user: postgres
  tags: mastodon
