---

- name: Setup Mastodon
  hosts: all
  become: true
  become_user: root
  roles:
    - role: common
    - role: timezone
    - role: git
    - role: nodejs
    - role: yarn
    - role: user
    - role: ruby
    - role: postgresql
