---

- name: Add yarn repository
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
  tags: yarn

- name: Install yarn
  yum:
    name: yarn
    update_cache: yes
  tags: yarn
