---

- name: Add DB user
  when: not is_docker
  postgresql_user:
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_user_password | password_hash('sha512') }}"
    encrypted: yes
    role_attr_flags: CREATEDB
  become: yes
  become_user: postgres
  tags:
    - postgresql
    - mastodon
