---

- name: Install dependencies
  yum:
    name: python-psycopg2
  tags: postgresql

- name: Add postgresql repository
  yum:
    name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
  tags: postgresql

- name: Install postgresql
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - postgresql10-server
    - postgresql10-contrib
  tags: postgresql

- name: Setup database
  when: not is_docker
  shell: "{{ postgresql_postgres_path }}/bin/postgresql-10-setup initdb"
  args:
    creates: /var/lib/pgsql/10/data/postgresql.conf
  tags: postgresql

- name: Start postgresql
  when: not is_docker
  systemd:
    name: postgresql-10
    enabled: yes
    state: started
  tags: postgresql
