---

- name: Install dependencies
  apt:
    name: python-psycopg2
  tags: postgresql

- name: Add postgresql repository
  template:
    src: pgdg.list.j2
    dest: /etc/apt/sources.list.d/pgdg.list
  tags: postgresql

- name: Add apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  tags: postgresql

- name: Install postgresql
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - postgresql-10
  tags: postgresql

- name: Start postgresql
  when: ansible_virtualization_type != "docker"
  systemd:
    name: postgresql
    enabled: yes
    state: started
  tags: postgresql

- name: Add DB user
  when: ansible_virtualization_type != "docker"
  postgresql_user:
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_user_password | password_hash('sha512') }}"
    encrypted: yes
    role_attr_flags: CREATEDB
  become: yes
  become_user: postgres
  tags: postgresql
