---

- name: Install dependencies
  apt:
    name: python-psycopg2
  tags: postgresql

- name: Add postgresql repository
  template:
    src: pgdg.list.j2
    dest: /etc/apt/sources.list.d/pgdg.list
  tags: postgresql

- name: Add apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  tags: postgresql

- name: Install postgresql
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - postgresql
    - postgresql-contrib
  tags: postgresql

- name: Start postgresql
  when: not is_docker
  systemd:
    name: postgresql
    enabled: yes
    state: started
  tags: postgresql
