---

- name: Add postgresql repository
  template:
    src: pgdg.list.j2
    dest: /etc/apt/sources.list.d/pgdg.list
  tags: postgresql

- name: Add apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  tags: postgresql

- name: Install postgresql
  apt:
    name: postgresql-10
    update_cache: yes
  register: hoge
  tags: postgresql

- name: postgres --version
  shell: postgres --version
  environment:
    PATH: "/usr/lib/postgresql/10/bin:{{ ansible_env.PATH }}"
  register: postgresql_installed_version
  tags: postgresql

- name: Installed version
  debug:
    msg: "installed: {{ postgresql_installed_version.stdout }}"
  tags: postgresql
