---

- name: Add postgresql repository
  template:
    src: pgdg.list.j2
    dest: /etc/apt/sources.list.d/pgdg.list
  tags: postgresql

- name: Add apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  tags: postgresql

- name: Install postgresql
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - postgresql-10
    - postgresql-10-contrib
  tags: postgresql
