---

- name: Include tasks
  include_role:
    name: postgresql
    tasks_from: "{{ item }}"
  with_first_found:
    - "{{ lower_distribution }}.yml"
    - "{{ lower_os_family }}.yml"
  tags: postgresql
