---

- name: Reload nginx
  when: not is_docker
  systemd:
    name: nginx
    state: reloaded
  tags: mastodon

- name: Daemon reload
  when: not is_docker
  systemd:
    daemon_reload: yes
  tags: mastodon
